# Generated by Django 4.1.3 on 2022-11-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhagatdetail',
            name='dataid',
        ),
    ]
