# Generated by Django 4.1.3 on 2022-11-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_bhagatdetail_dataid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhagatdetail',
            name='dataid',
            field=models.CharField(default='', max_length=6),
        ),
    ]
