# Generated by Django 4.1.3 on 2022-11-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_city_pradesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhagatdetail',
            name='pradesh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pradesh'),
        ),
    ]
