# Generated by Django 4.1.3 on 2022-11-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bhagatdetail_pradesh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
