# Generated by Django 4.1.3 on 2022-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhagatdetail',
            name='receiptNo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
