# Generated by Django 4.1.3 on 2022-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bhagatdetail_receiptno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhagatdetail',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='bhagatdetail',
            name='remark',
            field=models.CharField(default='', max_length=100),
        ),
    ]
