# Generated by Django 4.1.3 on 2022-12-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bhagatdetail_pincode_bhagatdetail_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhagatdetail',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
