# Generated by Django 4.1.3 on 2022-12-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bhagatdetail_dataid_alter_bhagatdetail_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhagatdetail',
            name='disCount',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
