# Generated by Django 4.1.3 on 2022-12-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_bhagatdetail_discount"),
    ]

    operations = [
        migrations.DeleteModel(name="BhagatDetail",),
    ]
