# Generated by Django 4.1.3 on 2022-12-07 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_delete_bhagatdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zoneName", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BhagatDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("districtCode", models.CharField(max_length=6)),
                ("disCount", models.CharField(max_length=6)),
                ("dataid", models.CharField(max_length=6)),
                ("receiptNo", models.CharField(max_length=15)),
                ("receiptDate", models.DateField(default=django.utils.timezone.now)),
                ("entryDate", models.DateField(default=django.utils.timezone.now)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("subYear", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("addressOne", models.CharField(max_length=100)),
                ("addressTwo", models.CharField(max_length=100)),
                ("addressThree", models.CharField(max_length=100)),
                ("is_zone", models.BooleanField()),
                ("phoneNum", models.CharField(max_length=10)),
                ("newFlag", models.BooleanField()),
                ("dontSendFlag", models.BooleanField()),
                ("pincode", models.CharField(max_length=6)),
                ("remark", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.city"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.district"
                    ),
                ),
                (
                    "pradesh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.pradesh",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.state"
                    ),
                ),
                (
                    "taluka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.taluka"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.zone"
                    ),
                ),
            ],
        ),
    ]
