# Generated by Django 4.1.3 on 2022-12-07 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_zone_bhagatdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bhagatdetail",
            name="addressOne",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="addressThree",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="addressTwo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.city"
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="dataid",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="disCount",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.district",
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="districtCode",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="entryDate",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="phoneNum",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="pincode",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="receiptDate",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="receiptNo",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="remark",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="state",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.state"
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="taluka",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.taluka"
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="zone",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.zone"
            ),
        ),
    ]
