# Generated by Django 4.1.3 on 2022-12-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_bhagatdetail_addressone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bhagatdetail",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
