# Generated by Django 4.1.3 on 2022-12-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_bhagatdetail_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bhagatdetail", name="is_active", field=models.BooleanField(),
        ),
    ]
