# Generated by Django 4.1.4 on 2022-12-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_bhagatdetail_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="bhagatdetail",
            name="qrcode",
            field=models.CharField(default="", max_length=10000, null=True),
        ),
    ]
