# Generated by Django 4.1.4 on 2022-12-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_bhagatdetail_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="bhagatdetail",
            name="redZone",
            field=models.BooleanField(default=False),
        ),
    ]
