# Generated by Django 4.1.4 on 2022-12-09 04:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_bhagatdetail_redzone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bhagatdetail",
            name="addressOne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="addressThree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="addressTwo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.city",
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="dataid",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="disCount",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.district",
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="districtCode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="entryDate",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="phoneNum",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="pradesh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.pradesh",
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="qrcode",
            field=models.CharField(blank=True, default="", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="receiptDate",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="receiptNo",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="remark",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.state",
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="taluka",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.taluka",
            ),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.zone",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="pradesh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.pradesh",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="districtCode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
