# Generated by Django 4.1.4 on 2023-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_bhagatdetail_addressone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bhagatdetail",
            name="cityName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bhagatdetail",
            name="districtName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bhagatdetail",
            name="pradeshName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bhagatdetail",
            name="stateName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bhagatdetail",
            name="talukaName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bhagatdetail",
            name="zoneName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
