# Generated by Django 4.1.4 on 2023-07-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_bhagatdetail_cityname_bhagatdetail_districtname_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bhagatdetail", name="city",),
        migrations.RemoveField(model_name="bhagatdetail", name="district",),
        migrations.RemoveField(model_name="bhagatdetail", name="pradesh",),
        migrations.RemoveField(model_name="bhagatdetail", name="state",),
        migrations.RemoveField(model_name="bhagatdetail", name="taluka",),
        migrations.RemoveField(model_name="bhagatdetail", name="zone",),
    ]
