# Generated by Django 4.1.4 on 2023-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_remove_bhagatdetail_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bhagatdetail",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="startDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bhagatdetail",
            name="subYear",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
