# Generated by Django 4.1.4 on 2023-08-12 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=1000, null=True)),
                ("pradesh", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adDescription",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("logo", models.CharField(blank=True, max_length=500, null=True)),
                ("extraFiles", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "extraDescription",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("oldPhoto", models.CharField(blank=True, max_length=500, null=True)),
                ("paymentMode", models.CharField(blank=True, max_length=10, null=True)),
                ("paymentId", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "onlinePaymentDetails",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("singleCount", models.IntegerField(blank=True, null=True)),
                ("multiCount", models.IntegerField(blank=True, null=True)),
                ("bankName", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "chequeNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("totalAmount", models.IntegerField(blank=True, null=True)),
                (
                    "accountHolderName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "receiptNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "referenceName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "referenceNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gstNo", models.CharField(blank=True, max_length=10, null=True)),
                ("panNo", models.CharField(blank=True, max_length=10, null=True)),
                ("isPaid", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "isApproved",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "isProcessing",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "isPrinted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "isDelivered",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "isRejected",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "isDeleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "isCompleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarform.calendaruser",
                    ),
                ),
            ],
        ),
    ]
