# Generated by Django 4.1.4 on 2023-08-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendaruser",
            name="isKaryakata",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
